/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package currencyconverter;

/**
 *
 * @author Cirilo
 */
public class ConvertLayout extends javax.swing.JFrame {

    /**
     * Creates new form ConvertLayout
     */
    public ConvertLayout() {
        initComponents();
        
    }
    //Variáveis
    int a,b = 0;
    Double valor = null;
    Double[][] Cotacao = {{1.0,5.20,0.82,103.68,0.73},
            {0.19,1.0,0.16,19.91,0.14},
            {1.22,6.33,1.0,126.17,0.89},
            {0.0096,0.05,0.0079,1.0,0.0071},
            {1.37,7.12,1.13,141.95,1.0}};
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Txt1 = new javax.swing.JTextField();
        Txt2 = new javax.swing.JTextField();
        jPanelL = new javax.swing.JPanel();
        B4L = new javax.swing.JRadioButton();
        B1L = new javax.swing.JRadioButton();
        B2L = new javax.swing.JRadioButton();
        B5L = new javax.swing.JRadioButton();
        B3L = new javax.swing.JRadioButton();
        jPanelR = new javax.swing.JPanel();
        B3R = new javax.swing.JRadioButton();
        B4R = new javax.swing.JRadioButton();
        B5R = new javax.swing.JRadioButton();
        B2R = new javax.swing.JRadioButton();
        B1R = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Txt1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N

        Txt2.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N

        buttonGroup1.add(B4L);
        B4L.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        B4L.setText("Yen");

        buttonGroup1.add(B1L);
        B1L.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        B1L.setText("Dólar");

        buttonGroup1.add(B2L);
        B2L.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        B2L.setText("Real");

        buttonGroup1.add(B5L);
        B5L.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        B5L.setText("Libra");

        buttonGroup1.add(B3L);
        B3L.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        B3L.setText("Euro");

        javax.swing.GroupLayout jPanelLLayout = new javax.swing.GroupLayout(jPanelL);
        jPanelL.setLayout(jPanelLLayout);
        jPanelLLayout.setHorizontalGroup(
            jPanelLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B1L)
                    .addComponent(B2L)
                    .addComponent(B4L)
                    .addComponent(B5L)
                    .addComponent(B3L))
                .addContainerGap())
        );
        jPanelLLayout.setVerticalGroup(
            jPanelLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B1L)
                .addGap(8, 8, 8)
                .addComponent(B2L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B3L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B4L)
                .addGap(8, 8, 8)
                .addComponent(B5L)
                .addContainerGap())
        );

        buttonGroup2.add(B3R);
        B3R.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        B3R.setText("Euro");

        buttonGroup2.add(B4R);
        B4R.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        B4R.setText("Yen");

        buttonGroup2.add(B5R);
        B5R.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        B5R.setText("Libra");

        buttonGroup2.add(B2R);
        B2R.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        B2R.setText("Real");

        buttonGroup2.add(B1R);
        B1R.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        B1R.setText("Dólar");

        javax.swing.GroupLayout jPanelRLayout = new javax.swing.GroupLayout(jPanelR);
        jPanelR.setLayout(jPanelRLayout);
        jPanelRLayout.setHorizontalGroup(
            jPanelRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B1R)
                    .addComponent(B4R)
                    .addComponent(B5R)
                    .addComponent(B3R)
                    .addComponent(B2R))
                .addContainerGap())
        );
        jPanelRLayout.setVerticalGroup(
            jPanelRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B1R)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B2R)
                .addGap(10, 10, 10)
                .addComponent(B3R)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B4R)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B5R)
                .addContainerGap())
        );

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)))
                .addComponent(jPanelR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addComponent(jPanelL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 24)); // NOI18N
        jTextField1.setText("Currency Converter  2020");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Txt2.setText("");
        valor = Double.parseDouble(Txt1.getText());
        
        if(B1L.isSelected()){
            a =0;
        }else if(B2L.isSelected()){
            a =1;
        }else if(B3L.isSelected()){
            a =2;
        }else if(B4L.isSelected()){
            a =3;
        }else if(B5L.isSelected()){
            a =4;
        }
        
        if(B1R.isSelected()){
            b =0;
        }else if(B2R.isSelected()){
            b =1;
        }else if(B3R.isSelected()){
            b =2;
        }else if(B4R.isSelected()){
            b =3;
        }else if(B5R.isSelected()){
            b =4;
        }
        
         valor *= Cotacao[a][b];
        
        Txt2.setText(String.valueOf(valor).format("%.2f",valor));
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton B1L;
    private javax.swing.JRadioButton B1R;
    private javax.swing.JRadioButton B2L;
    private javax.swing.JRadioButton B2R;
    private javax.swing.JRadioButton B3L;
    private javax.swing.JRadioButton B3R;
    private javax.swing.JRadioButton B4L;
    private javax.swing.JRadioButton B4R;
    private javax.swing.JRadioButton B5L;
    private javax.swing.JRadioButton B5R;
    private javax.swing.JTextField Txt1;
    private javax.swing.JTextField Txt2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelL;
    private javax.swing.JPanel jPanelR;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
